### ISSUE TITLE
Doesn't WORK on WHMCS 7.2.3

### ISSUE THREAD

**Issue by dackoni** [liquidweb/LiquidWeb-WHMCS-Plugin#10]
I have problem with LuquidWeb WHMCS plugin. I intalled them, activated, entered API and go (Registred reseller, partner status). Just made several test VPS with Liquid Web Product Setup. Everything seems OK. But when I was trying to enable billing through Liquid Web Storm Servers Billing, nothing happens. I selected one of VPS from drop down menu and nothing. I should be view a list of add ons for the made vps or d/server, but i was not. Plugin doesn't WORK. 
Please HELP.
I also found some errors on Liquid Web Storm Servers Billing page and on Liquid Web Product Setup page.
(image attachments)
![liquid-web-product-setup](https://user-images.githubusercontent.com/30274578/28361062-be32cb94-6c77-11e7-8fbb-b03a06b51e45.png)
![liquid web storm servers billing](https://user-images.githubusercontent.com/30274578/28361067-c5be612a-6c77-11e7-9be3-a472670527d9.png)

**Comment by santhoshsuvarna** [comment]
We are looking at this and fix it at the earliest.

**Comment by santhoshsuvarna** [comment]
@dackoni above issue is fixed in latest version 1.2.5 and is available in GIT
