### ISSUE TITLE
[BUG] API login redirect issues

### ISSUE THREAD

**Issue by mallardduck** [liquidweb/LiquidWeb-WHMCS-Plugin#3]
Upon the initial usage of Product Setup Wizard, if you choose to manually provide a set of API credentials you will be redirected to the SSD VPS configuration page of the product setup wizard. It doesn't matter if you selected Cloud, or VPS, you always end up at the VPS page.

This is only a very minor issue, as it will only come up during the initial setup when the plugin needs to configure API access. As this is only done once per WHMCS install it's not likely that this will come up too often.

Update: After reviewing further, it seems that you will be provided with both the product wizards similar to if both boxes were checked when you started the process.

**Comment by santhoshsuvarna** [comment]
We did not find any issue with regards to above scenario.
