### ISSUE TITLE
[BUG] Order summary displaying hidden options

### ISSUE THREAD

**Issue by mallardduck** [liquidweb/LiquidWeb-WHMCS-Plugin#6]
For customize-able options you have the ability to hide/remove them from the public facing list. When you have adjusted a customable options to be hidden, the option should not be included or shown in the Order Summary either.

Pics to come.

**Comment by mallardduck** [comment]
As you can see in the following picture I have a number of options hidden:

![Hidden selected](http://imgur.com/k4t6ApN.jpeg)

But for some reason these items are being shown on the Order summary here:

![Order Summary](http://imgur.com/gKbWvub.jpeg)

Items outlined with red dots should not be shown at all as they are hidden from the customers selection.

**Comment by santhoshsuvarna** [comment]
There is no issue. Hidden configurable options does not display in cart.
