### ISSUE TITLE
Doesn't work with WHMCS 7.2

### ISSUE THREAD

**Issue by urdave** [liquidweb/LiquidWeb-WHMCS-Plugin#9]
Installed and activated, doesn't show up under addon menu tab. And I was just approved as a reseller...

**Comment by Duplika** [comment]
Create a new product and there, see if you are able to select and login to LiquidWeb at the Module Settings tab.

**Comment by mallardduck** [comment]
There is a [KB series](https://www.liquidweb.com/kb/what-is-whmcs-and-installing-the-liquid-web-plugin/) here which details setup, creating your initial api connection and covers basic product creations.

I believe it sounds like you may be able to pickup around the [second page](https://www.liquidweb.com/kb/whmcs-account-setup-the-product-setup-wizard-and-storm-servers-billing/) detailing the process that @Duplika  explained.

**Comment by mallardduck** [comment]
@urdave Unless your issue was related to #10 (which is now resolved as well), I'm gonna guess that you've found a solution so I'll close this. If I'm incorrect do not hesitate to open a new issue or correct me here and we can re-open.
